-- Clients bulk import
-- Run from project root: sqlite3 ticketdash.db < calendar_import.sql
-- (or whatever your DB filename is)

INSERT OR IGNORE INTO clients (name, is_critical) VALUES
('Wezen SRL', 1),
('PwC US Group LLP', 1),
('Unidasul Distribuidora Alimentar', 1),
('Tecidos e Armarinhos Miguel', 1),
('Reliper S.A.', 1),
('Dellamed S.A.', 1),
('Distribuidora Farmaceutica', 1),
('Lansing Building Products', 1),
('Alcaldia De Medellin', 1),
('Ibema Companhia Brasileira', 1),
('Tuberfil Industria e Comercio', 1),
('Independence Drilling S.A.', 1),
('Dohler S/A', 1),
('Armorlitte S. A.', 1),
('Plastilene S.A.', 1),
('Parque Arauco S.A.', 1),
('Unimaco S.A.', 1),
('Blue Express S.A.', 1),
('Divino S.A.', 1),
('Automercado San Diego C.A.', 1),
('SSM Health Care Corporation', 1),
('Valco Instruments Company', 1),
('Grupo Industrial Donde S.A.', 1),
('Frigorificos De Guatemala', 1),
('Wonder Brands Inc', 1),
('Real Moto Pecas Ltda', 1),
('Nikola Corporation', 1),
('Pottencial Seguradora S/A', 1),
('Alianza Compania de Seguros', 1),
('Agricola Nacional S.A.C.E.I.', 1),
('Salmones Aysen S.A.', 1),
('Frigorifico Temuco S.A.', 1),
('Distrisoda S.A.', 1),
('Laboratorios Lansier S.A.C.', 1),
('TECNOVAX S.A.', 1),
('Luiz Guilherme Sartori & Cia', 1),
('Naturgy Ban S.A.', 1),
('Hidroelectrica La Higuera S.A.', 1),
('360 Energy S.A.', 1),
('Crescent Energy Company', 1),
('ThompsonGas LLC', 1),
('The Boelter Companies Inc', 1),
('Mingledorff''s Inc', 1),
('Tessco Technologies LLC', 1),
('Gas Uribe S.A. de C.V.', 1),
('Atalco Gramercy LLC', 1),
('Array Tech Inc', 1),
('Comfrut S.A', 1),
('Dole Packaged Foods LLC', 1),
('Postobon S.A.', 1),
('Red Hat LLC', 1),
('Domino''s Pizza LLC', 1),
('Mathiesen S.A.C.', 1),
('Bethel Church of Redding', 1),
('CLOVER Internacional C.A.', 1),
('Rinchem Company LLC', 1),
('The Chamberlain Group LLC', 1),
('Industrias de Hule Galgo S.A.', 1),
('Electrify America LLC', 1),
('Suramericana S.A.', 1),
('Nationwide Mutual Insurance', 1),
('Hunt Consolidated Inc.', 1),
('Bunge North America Inc.', 1),
('NBA Properties Inc.', 1),
('Rumpke of Ohio Inc.', 1),
('Bruks Siwertell AB', 1),
('SOLEIL MINING', 1),
('BMT INTERNATIONAL NV', 1),
('W J Towell LLC', 1),
('Zijin Zhixin Technology', 1),
('Testo Industrial Services GmbH', 1),
('LLC MC Resourse Finance', 1),
('Brandcare Est 2014 SA', 1),
('Bangkok Komatsu Sales', 1),
('Chorus Research Engineering', 1),
('Hans Willi Bohmer GmbH', 1),
('GREENWEEE INTERNATIONAL', 1),
('MLADINSKA KNJIGA TRGOVINA', 1),
('FARMALOGIST', 1),
('Aspen Glove Sdn Bhd', 1),
('Tongding interconnection inc', 1),
('Zijin Mining Group Co. Ltd.', 1),
('ISI Steel Co. Ltd.', 1),
('INDUSTRIAS MURTRA S.A.', 1),
('International Company Egypt', 1),
('INDUSTRIA TECNICA DEL SUR', 1),
('Great Deals E-Commerce Corp', 1),
('katerra India Private Limited', 1),
('Abdulla Fouad Company', 1),
('AlRomaih Industrial Commercial', 1),
('SERVICIO PUBLICO DE EMPLEO', 1),
('Organismo Autonomo Informatica', 1),
('ADP AGUAS DE PORTUGAL', 1),
('Public Service Department UAE', 1),
('Muncipal Corporation of Greater', 1),
('Ceylon Biscuits ltd', 1),
('Ardo Foods NV', 1),
('SOFIYA QANDOLAT LLC', 1),
('Paulaner Brauerei Gruppe GmbH', 1),
('Eve Power Hungary Kft.', 1),
('AB INBEV EFES AO', 1),
('Winkels Getranke Logistik GmbH', 1),
('Lunch Garden Holding NV', 1),
('SNCF RESEAU', 1),
('Cambodia Airport Investment', 1),
('INTERNATIONAL ALEXANDER', 1),
('YEONG CHIN Machinery', 1),
('AEM Holdings Ltd', 1),
('SEATRIUM LIMITED', 1),
('Incab LLC', 1),
('CT PACK SRL', 1),
('CAN ULUSLARARASI YATIRIM', 1),
('BT Payment Services Nigeria', 1),
('Colruyt Group Services', 1),
('Colruyt Group nv', 1),
('Biyue Beijing Technology', 1),
('Sun Race Sturmey-Archer Inc', 1),
('Bosch China Investment Ltd', 1),
('SAIC HK Limited', 1),
('Cycle & Carriage Bintang Bhd', 1),
('MG JW Automobile Pakistan', 1),
('VinFast Germany GmbH', 1),
('University Hospitals Birmingham', 1),
('Sky Italia S.r.l.', 1),
('PT Alamtri Resources Indonesia', 1),
('VSM-Vereinigte Schmirgel', 1),
('Herbert Waldmann GmbH', 1),
('Alibaba Cloud Computing Ltd', 1),
('ADATA Technology Co. Ltd.', 1),
('Testo SE & Co. KGaA', 1),
('Husqvarna AB', 1),
('Nilkamal Limited', 1),
('Rauch Fruchtsafte GmbH', 1),
('BELROS RETAIL S.A.', 1),
('JYSK SE', 1),
('Toya S.A.', 1),
('Carl Geringhoff GmbH', 1),
('Pirelli & C. S.p.A.', 1),
('STELLANTIS EUROPE SPA', 1),
('NTF INDIA PRIVATE LIMITED', 1),
('OOO Volgo-Don AgroInvest', 1),
('ENI S.p.A.', 1),
('SAP MCD Service Engineering', 1),
('Department of Corrections NZ', 1),
('Weston Foods Canada Inc', 1),
('Adient US LLC', 1),
('777 Partners LLC', 1),
('Clear Sale S.A.', 1),
('Unipar Carbocloro S.A.', 1),
('Ascenty Data Centers', 1),
('SONDA S.A.', 1),
('Sonae Arauco Portugal S.A.', 1),
('Ball Corporation', 1),
('Banco Macro S.A.', 1),
('Corona Industrial S.A.S', 1),
('Envalior B.V', 1),
('Cooperatieve Rabobank U.A.', 1),
('Raysut Cement Company', 1),
('Davide Campari Milano N.V.', 1),
('Barry Callebaut Services NV', 1),
('D. Swarovski KG', 1),
('ENAIRE', 1),
('Latam Airlines Group S.A.', 1),
('Crosland Servicios Administrativos', 1),
('Sigma Company Limited', 1),
('Concesionaria Vuela Compania', 1),
('Border States Industries Inc.', 1),
('SNCB', 1),
('Breakthru Beverage Group', 1),
('NTPC Limited', 1),
('Suomen Osuuskauppojen Keskuskunta', 1),
('Bruder Schlau GmbH', 1),
('HCCOM SA', 1),
('Grupo Marti S.A. de C.V.', 1),
('Cooperativa Dos Plantadores', 1),
('Shutterfly LLC', 1),
('Arburg GmbH + Co KG', 1),
('Danfoss A/S', 1),
('IKEA IT AB', 1),
('PT Astra Honda Motor', 1),
('AVL List GmbH', 1),
('Los Portales S.A.', 1),
('BMW Brilliance Automotive', 1),
('Harley-Davidson Inc.', 1),
('DEUTZ Aktiengesellschaft', 1),
('Bridgestone Asia Pacific', 1),
('Mercedes-Benz Grand Prix', 1),
('Grupa Azoty S.A.', 1),
('Benjamin Moore & Co', 1),
('Sopharma Trading AD', 1),
('Vision Service Plan', 1),
('Icatu Seguros S/A', 1),
('Woodside Energy Limited', 1),
('Cimpress USA Incorporated', 1),
('Tyson Foods Inc.', 1),
('Mimo Tech Co. Ltd.', 1),
('Proximus S.A. de droit public', 1),
('Al Khaleej Sugar Co LLC', 1),
('Frisa Forjados S.A. de C.V.', 1),
('Fondazione Human Technopole', 1),
('Al Ahli Hospital', 1),
('Agricola Cerro Prieto S.A.', 1),
('Aramco Overseas Company', 1),
('MRS Logistica S/A.', 1),
('Minera Don Nicolas S.A.', 1),
('Hannover Ruck SE', 1),
('ESPRESSO AMERICANO S A', 1),
('Apex Health Care Mfg. Inc.', 1),
('Vistra Corporate Services', 1),
('IBM India Pvt Ltd', 1),
('Comercializadora GONAC', 1),
('Nobia AB', 1),
('Bru Textiles NV', 1),
('BRFertil S/A.', 1),
('Phillips 66 Company', 1),
('IBM Corporation', 1),
('El Palacio de Hierro S.A.', 1),
('Egyptian Union for Construction', 1),
('MULTIVAC Sepp Hagenmayer', 1),
('Qassim Cement Company', 1),
('Autoservicio Mayorista Diario', 1),
('Petrobras Bolivia S.A.', 1),
('Acme Intralog FZCO', 1),
('PT APP Purinusa Ekapersada', 1),
('GOTW Pty Ltd', 1),
('MUNDYS SPA', 1),
('Samvardhana Motherson International', 1),
('CORDES & GRAEFE KG', 1),
('United HealthCare Services', 1),
('EnBW Energie Baden-Wurttemberg', 1),
('dmTECH GmbH', 1),
('PricewaterhouseCoopers Canada', 1),
('Manweir', 1),
('NEXUS ENERGIA S.A.', 1),
('Industrial Danec S.A.', 1),
('The Andersons Inc.', 1),
('FCA ITEM S.p.A.', 1),
('Abdulhadi Abdullah Al Qahtani', 1),
('BFORBANK', 1),
('Corning Incorporated', 1),
('Wienerberger AG', 1),
('Promocionales de Occidente', 1),
('Klabin S.A.', 1),
('CORMAN SPA', 1),
('WIZ CHEMICALS SRL', 1),
('SOFITEC AERO', 1),
('Fisker Group Inc.', 1),
('Termoelectrica Jose de San Martin', 1),
('Kinjal Civilcon LLP', 1),
('Beaumont New Ammonia LLC', 1),
('Ike Grupo Empresarial S.A.', 1),
('Inmobiliaria y Promotora Roca', 1);
